Repository baobabsoluciones/mango, pull requests merged in 2024-07, with the labels that each got.

#127 Changed the MacOS version. the latest has an M1 chip and has problems…
  .github/workflows/mango_unit_testing.yml
Labels: bug

#125 Feature/countries in arcgis
  mango/clients/arcgis.py
Labels: bug, enhancement

#129 Release/v0.2.2
  changelog.rst
  docs/source/dev/benchmark.rst
  docs/source/dev/index.rst
  docs/source/dev/models.rst
  docs/source/dev/processing.rst
  docs/source/dev/table.rst
  docs/source/refs.bib
  mango/__init__.py
  mango/benchmark/optimization/gramacy_lee.py
  mango/benchmark/optimization/griewank.py
  mango/benchmark/optimization/holder_table.py
  mango/benchmark/optimization/langermann.py
  mango/benchmark/optimization/levy.py
  mango/benchmark/optimization/rastrigin.py
  mango/benchmark/optimization/rosenbrock.py
  mango/benchmark/optimization/schaffer.py
  mango/benchmark/optimization/schwefel.py
  mango/clients/arcgis.py
  mango/clients/google_cloud_storage.py
  mango/config/base_config.py
  mango/dashboards/file_explorer_app.py
  mango/models/pyomo.py
  mango/processing/date_functions.py
  mango/processing/file_functions.py
  mango/processing/object_functions.py
  mango/table/pytups_table.py
  mango/table/pytups_tools.py
  mango/table/table_tools.py
  mango/tests/config_module/test_config.py
  mango/tests/models_module/test_optimization_benchmarks.py
  mango/tests/processing_module/test_date_functions.py
  mango/tests/processing_module/test_file_functions.py
  mango/tests/table_module/test_table.py
  pyproject.toml
Labels: bug, enhancement

#134 Added codeowners file
  .github/CODEOWNERS
Labels: enhancement

#135 Added codeowners file (#134)
  .github/CODEOWNERS
Labels: enhancement

#140 Relax requirements (#139)
  .github/workflows/mango_unit_testing.yml
  changelog.rst
  mango/__init__.py
  pyproject.toml
  requirements-dev.txt
  requirements.txt
Labels: enhancement
